int32 polygon_mode
int32 intepolation_mode
int32 smooth_mode

---

int32 result

# # # Request codes

# # polygon_mode
# int32 Konvexhull = 0
# int32 Sequentiell = 1
# int32 Room_Walls = 2

# # intepolation_mode

# # smooth_mode

